version: '3.8'

services:
  # PostgreSQL Database
  postgres:
    image: postgres:15-alpine
    container_name: ricemillos-postgres
    environment:
      POSTGRES_DB: ricemillos_dev
      POSTGRES_USER: ricemillos
      POSTGRES_PASSWORD: password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./tools/docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - ricemillos-network
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ricemillos"]
      interval: 10s
      timeout: 5s
      retries: 5

  # Redis Cache
  redis:
    image: redis:7-alpine
    container_name: ricemillos-redis
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    networks:
      - ricemillos-network
    healthcheck:
      test: ["CMD", "redis-cli", "ping"]
      interval: 10s
      timeout: 5s
      retries: 5

  # API Development Server
  api:
    build:
      context: .
      dockerfile: ./apps/api/Dockerfile.dev
    container_name: ricemillos-api
    environment:
      - NODE_ENV=development
      - DATABASE_URL=postgresql://ricemillos:password@postgres:5432/ricemillos_dev
      - REDIS_URL=redis://redis:6379
    ports:
      - "3001:3001"
    volumes:
      - ./apps/api:/app/apps/api
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/api/node_modules
    depends_on:
      postgres:
        condition: service_healthy
      redis:
        condition: service_healthy
    networks:
      - ricemillos-network
    command: npm run dev

  # Web Development Server
  web:
    build:
      context: .
      dockerfile: ./apps/web/Dockerfile.dev
    container_name: ricemillos-web
    environment:
      - NODE_ENV=development
      - NEXT_PUBLIC_API_URL=http://localhost:3001/api/v1
    ports:
      - "3000:3000"
    volumes:
      - ./apps/web:/app/apps/web
      - ./packages:/app/packages
      - /app/node_modules
      - /app/apps/web/node_modules
    depends_on:
      - api
    networks:
      - ricemillos-network
    command: npm run dev

  # Database Administration
  pgadmin:
    image: dpage/pgadmin4:latest
    container_name: ricemillos-pgadmin
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@ricemillos.com
      PGADMIN_DEFAULT_PASSWORD: admin123
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    ports:
      - "5050:80"
    volumes:
      - pgadmin_data:/var/lib/pgadmin
    depends_on:
      - postgres
    networks:
      - ricemillos-network

volumes:
  postgres_data:
    driver: local
  redis_data:
    driver: local
  pgadmin_data:
    driver: local

networks:
  ricemillos-network:
    driver: bridge